### ISSUE TITLE
Find good public datasets that we can use for analysis already

### ISSUE THREAD

**Issue by gsaurabhr** [csndl-iitd/visual-attention#4]
@shreyagakhar @Mridul-06 Add the list of all good potential datasets you used. Which one do you use finally, and why?

**Comment by shreyagakhar** [comment]
Potential datasets: 

1. BOLD 5000: https://openneuro.org/datasets/ds001499/versions/1.3.0
2. Natural Object Dataset (NOD): https://openneuro.org/datasets/ds004496/versions/2.1.2
